### ISSUE TITLE
Execution

### ISSUE THREAD

**Issue by jahidhasanlinix** [wirzka/netfier#4]
What is the exact command syntax to run this code and see the changes?

**Comment by wirzka** [comment]
In order to run the script you have to insert your own API key in the source code. Then, launch the script without any arguments.

Please, if the code's not working, let me know, and I'll fix it asap.
Thanks.

-wirzka.

**Comment by jahidhasanlinix** [comment]
Just curious, how can get the API key? I opened the link from readme file, it redirect me to a IP checker site. Can you please help regarding Api generation part, how to do that exactly

**Comment by wirzka** [comment]
The link brings you to the service's website used by netfier.
You can get the API key by creating an AbuseIPDB account. Check this page for more information: https://www.abuseipdb.com/api.

Once you got one, insert it here: https://github.com/wirzka/netfier/blob/8aea272b1b0933794eadf13b39929a60fdd106d5/netfier.py#L29.

Let me know if you need more help. In the meanwhile, I'll update the readme with the specific link to the API documentation.

**Comment by wirzka** [comment]
> Just curious, how can get the API key? I opened the link from readme file, it redirect me to a IP checker site. Can you please help regarding Api generation part, how to do that exactly

Hey, can I close your issue?

**Comment by jahidhasanlinix** [comment]
Sure
